apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-volume-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: microk8s-hostpath
  resources:
    requests:
      storage: 500M
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-volume-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: microk8s-hostpath
  resources:
    requests:
      storage: 500M
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: squeakywheel/postgres:edge
        env:
        - name: POSTGRES_PASSWORD
          value: "secret"
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data/
        ports:
        - containerPort: 5432
          name: postgres
          protocol: TCP
      - name: telegraf
        image: squeakywheel/telegraf:edge
        env:
        - name: HOST_PROC
          value: "/hostfs/proc"
        - name: HOST_SYS
          value: "/hostfs/sys"
        volumeMounts:
        - name: telegraf-config-volume
          mountPath: /etc/telegraf/telegraf.conf
          subPath: telegraf.conf
        - name: hostfs-proc
          mountPath: /hostfs/proc
          readOnly: true
        - name: hostfs-sys
          mountPath: /hostfs/sys
          readOnly: true
        ports:
        - containerPort: 9273
          name: telegraf
          protocol: TCP
      volumes:
        - name: hostfs-proc
          hostPath:
            path: /proc
            type: Directory
        - name: hostfs-sys
          hostPath:
            path: /sys
            type: Directory
        - name: telegraf-config-volume
          configMap:
            name: telegraf-config
            items:
            - key: telegraf
              path: telegraf.conf
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgresql-volume-claim
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
      - name: prometheus
        image: squeakywheel/prometheus:edge
        volumeMounts:
        - name: prometheus-config-volume
          mountPath: /etc/prometheus/prometheus.yml
          subPath: prometheus.yml
        - name: prometheus-config-volume
          mountPath: /etc/prometheus/alerts.yml
          subPath: alerts.yml
        - name: prometheus-data
          mountPath: /prometheus
        ports:
        - containerPort: 9090
          name: prometheus
          protocol: TCP
      - name: alertmanager
        image: squeakywheel/prometheus-alertmanager:edge
        volumeMounts:
        - name: alertmanager-config-volume
          mountPath: /etc/alertmanager/alertmanager.yml
          subPath: alertmanager.yml
        ports:
        - containerPort: 9093
          name: alertmanager
          protocol: TCP
      volumes:
        - name: prometheus-config-volume
          configMap:
            name: prometheus-config
            items:
            - key: prometheus
              path: prometheus.yml
            - key: prometheus-alerts
              path: alerts.yml
        - name: prometheus-data
          persistentVolumeClaim:
            claimName: prometheus-volume-claim
        - name: alertmanager-config-volume
          configMap:
            name: alertmanager-config
            items:
            - key: alertmanager
              path: alertmanager.yml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: squeakywheel/grafana:edge
        volumeMounts:
        - name: grafana-config-volume
          mountPath: /etc/grafana/provisioning/datasources/datasource.yml
          subPath: datasource.yml
        - name: grafana-config-volume
          mountPath: /etc/grafana/provisioning/dashboards/dashboard.yml
          subPath: dashboard.yml
        - name: grafana-config-volume
          mountPath: /etc/grafana/provisioning/dashboards/system-stats-dashboard.json
          subPath: system-stats-dashboard.json
        ports:
        - containerPort: 3000
          name: grafana
          protocol: TCP
      volumes:
        - name: grafana-config-volume
          configMap:
            name: grafana-config
            items:
            - key: grafana-datasource
              path: datasource.yml
            - key: grafana-dashboard-definition
              path: dashboard.yml
            - key: grafana-dashboard
              path: system-stats-dashboard.json
