apiVersion: 1

datasources:
  - name: prometheus-microk8s
    type: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus-service:9090
    basicAuth: false
    isDefault: true
    editable: true
