version: '2'

services:
    prometheus:
        image: kanashiro/prometheus:2.20.1-1
        network_mode: "host"
        ports:
            - 9090:9090
        volumes:
            - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
            - ./config/alerts.yml:/etc/prometheus/alerts.yml

    node-exporter:
        image: prom/node-exporter
        network_mode: "host"
        ports:
            - 9100:9100

    telegraf:
        image: kanashiro/telegraf:1.15.2
        network_mode: "host"
        ports:
            - 9273:9273
        volumes:
            - ./config/telegraf.conf:/etc/telegraf/telegraf.conf

    alertmanager:
        image: kanashiro/prometheus-alertmanager:0.21.0-1
        network_mode: "host"
        ports:
            - 9093:9093
        volumes:
            - ./config/alertmanager.yml:/etc/alertmanager/alertmanager.yml

    grafana:
        image: grafana/grafana:7.1.3-ubuntu
        network_mode: "host"
        ports:
            - 3000:3000
        volumes:
            - ./config/grafana/provisioning/:/etc/grafana/provisioning/

    cortex:
        image: cortexproject/cortex:v1.2.0
        network_mode: "host"
        ports:
            - 9009:9009
        volumes:
            - ./config/cortex.yaml:/etc/cortex/cortex.yaml
        command: [
            "-config.file=/etc/cortex/cortex.yaml"
            ]
